---
title: "static_testing"
author: "Gillian McGinnis"
date: "5/7/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(genius)
library(magrittr)
library(sentimentr)
library(tidytext)
library(ggthemes)
library(viridis)
library(wordcloud)
```

```{r inputs}
artist_of_interest <- "alt-J"
albums_of_interest <- c("An Awesome Wave", "This Is All Yours", "RELAXER")
dropwords <- NULL
```

```{r get_lyrics}
get_lyrics <- function(artist_input, albums_input){
  list_of_albums <- as.data.frame(albums_input) %>%
    rowid_to_column() %>%
    mutate(album = as.character(rowid))
  
  albums_input %>%
    map_dfr(.f = genius_album, artist = {{artist_input}}, .id = "album") %>%
    left_join(list_of_albums) %>%
    select(!album) %>%
    rename(album = albums_input) %>%
    mutate(album = fct_relevel(as.factor(album), {{albums_input}}))
}
```


```{r get_lyrics_manual, eval=FALSE}
listy_albums <- c("An Awesome Wave", "Odelay")
listy_artists <- c("alt-J", "Beck")

listy_df <- data.frame(artist = listy_artists, album = listy_albums)


genius_album(artist = "alt-J", album = "An Awesome Wave")
genius_album(artist = "Beck", album = "Odelay")

system.time(genius_album(artist = "alt-J", album = "An Awesome Wave"))
system.time(genius_album(artist = "Beck", album = "Odelay"))

pmap_dfr(
  .f = genius_album,
  .l = listy_df
) %>% view()


listy_df %>% 
  add_genius(artist, album, type = "lyric")

map2_dfr(
  listy_artists,
  listy_albums,
  .f = genius_album
)

tiay <- genius_album("alt-J", "This is all yours")

listy_tiay <- tiay %>% 
  distinct(track_title) %>% 
  mutate(artist = "alt-J") %>% 
  rename(track = track_title)

listy_tiay %>% 
  add_genius(artist, track, type = "lyrics")

data.frame(
  artist = c("alt-J", "alt-J"),
  song = c("Every Other Freckle", "Left Hand Free")
) %>% 
  group_by(song) %>% 
  pmap(genius_lyrics)

listy_tiay %>% 
  rename("song" = "track") %>% 
  select(artist, song) %>% 
  group_by(song) %>% 
  pmap(
    genius_lyrics
  )

```

```{r genius_ex, eval = FALSE}
artist_albums <- tribble(
 ~artist, ~album,
 "J. Cole", "KOD",
 "Sampha", "Process"
)


artist_albums %>%
 add_genius(artist, album, type = "track")
```



```{r getting_lyrics}
my_lyrics <- get_lyrics(artist_of_interest, albums_of_interest)

glimpse(my_lyrics)
```

```{r getting_lyrics_new}
artist_album <- data.frame(
  artist = c("New Order", "Beck", "Beck"),
  album = c("Power Corruption and Lies", "Odelay", "The Information")
)

genius_testy <- artist_album %>% 
  add_genius(artist, album, type = "album") %>% 
  mutate(
    album = fct_inorder(as.factor(album)),
    artist = fct_inorder(as.factor(artist)),
    track_title = fct_reorder(as.factor(track_title), track_n)
    )


genius_testy %>%
  unnest_tokens(output = word, input = lyric, token = "words") %>% 
    inner_join(get_sentiments("nrc")) %>%
    count(album, artist, sentiment) %>% 
      mutate(cat = case_when(
        (sentiment == "positive" | sentiment == "negative") ~ "Sentiment",
        TRUE ~ "Emotion")
      ) %>% 
  #mutate(sentiment = str_to_title(sentiment)) %>% 
      ggplot(aes(x = n,
                 y = fct_rev(sentiment),
                 fill = album,
                 color = artist)) +
      #facet_grid(vars(cat), vars(artist), scales = "free_y", space = "free_y") +
      facet_grid(vars(cat), scales = "free_y", space = "free_y") +
      geom_col(position = position_dodge2(reverse=TRUE)) +
  geom_text(aes(label=n), position = position_dodge2(0.9, reverse = TRUE), hjust = 1.25, color="black")+
      theme_hc(style = "darkunica") +
      theme(
        legend.position = "bottom",
        legend.box = "vertical",
        axis.text = element_text(color = "gray", size = 12)
      ) +
      labs(
        title = paste("NRC Sentiment Analysis"),
        x = "Word count",
        y = "",
        fill = "Album:",
        color = "Artist:"
      ) +
      scale_color_brewer(palette = "Dark2") +
      scale_fill_brewer(palette = "Set3")
```




```{r sentiment_sentences}
# my_lyrics %>% 
#   mutate(lyric_split = get_sentences(lyric)) %$% 
#   sentiment_by(lyric_split, list(track_title, album))

sentences <- my_lyrics %>% 
  get_sentences() %$%
  sentiment_by(lyric, list(track_title, album))

sentences %>% 
  ggplot(aes(x = ave_sentiment, y = track_title, color = album)) +
  geom_point()

my_lyrics %>%
  get_sentences() %$% 
  profanity_by(lyric, list(track_title, album)) %>% 
  arrange(desc(profanity_count)) %>% 
  mutate_at(c("sd", "ave_profanity"), round, digits = 3)


```

```{r text_highlighting}
my_lyrics %>% 
  #filter(track_title == "Breezeblocks") %>% 
  mutate(lyric_line = get_sentences(lyric)) %$%
  sentiment_by(lyric_line, list(track_title, album)) %>% 
  #sentiment_by(track_title, album) %>% 
  highlight()

my_lyrics %>% 
  mutate(lyric_line = get_sentences(lyric)) %$%
  sentiment_by(lyric_line, list(track_title, album)) %>% 
  highlight(
    open = FALSE
  )
```

```{r afinn}
album_afinn <- function(lyrics_df,
                        color_pal = "plasma",
                        scale_option = "free_y"){
  lyrics_df %>%
    unnest_tokens(output = word, input = lyric, token = "words") %>% 
    group_by(album, track_title) %>%
    mutate(index = round(line / max(line) * 100)) %>%
    inner_join(get_sentiments("afinn")) %>%
    ungroup() %>%
    count(album, index = index, wt = value) %>%
    ggplot(aes(x = index, y = n, fill = n)) +
    facet_grid(rows = vars(album), scales = {{scale_option}}) +
    geom_col() +
    theme_few() +
    labs(
      x = "Relative line position (% through song)",
      y = "Sentiment value",
      fill = "Sentiment value: ",
      title = paste("Sentiment analysis of select", {{artist_of_interest}}, "albums"),
      subtitle = "Net sentiment value by relative line position across all songs in an album.",
      caption = "Sentiment data provided by Finn Arup Nielsen"
      ) +
    geom_hline(yintercept = 0, color = "black") +
    theme(legend.position = "bottom") +
    scale_fill_viridis(option = {{color_pal}})
}

album_afinn(my_lyrics)
```

```{r afinn_artists}
genius_testy %>% 
  unnest_tokens(output = word, input = lyric, token = "words") %>% 
  group_by(album, artist, track_title) %>%
    mutate(index = round(line / max(line) * 100)) %>%
    inner_join(get_sentiments("afinn")) %>%
    ungroup() %>%
    count(album, index = index, wt = value) %>%
    ggplot(aes(x = index, y = n, fill = n)) +
    facet_grid(rows = vars(album), scales = "free_y") +
    geom_col() +
    theme_few() +
    labs(
      x = "Relative line position (% through song)",
      y = "Sentiment value",
      fill = "Sentiment value: ",
      title = paste("AFINN sentiment analysis"),
      subtitle = "Net sentiment value by relative line position across all songs in an album.",
      caption = "Sentiment data provided by Finn Arup Nielsen"
      ) +
    geom_hline(yintercept = 0, color = "black") +
    theme(legend.position = "bottom") +
    scale_fill_viridis(option = "plasma")
```

```{r wordcloud}
drop_words <- c("yeah")
min_freq <- 3
artist_input <- "Beck"
album_input <- "Odelay"

genius_testy %>% 
  unnest_tokens(output = word, input = lyric, token = "words") %>% 
  anti_join(stop_words, by = "word") %>%
  group_by(artist, album) %>% 
    count(word, sort = TRUE) %>%
    filter(!word %in% drop_words) %>%
  filter(
    artist == artist_input,
    album == album_input
    ) %>% 
    with(wordcloud(word,
                   n,
                   min.freq = min_freq,
                   random.order = FALSE,
                   #colors = {{color_pal}}))
                   colors = inferno(20, direction = -1, end = .9)))

artist_list <- "Beck, Mini Mansions, Beck"

unique(c(unlist(str_split(artist_list, ", "))))

genius_testy %>% 
  get_sentences() %$% 
  profanity_by(lyric, list(track_title, album, artist)) %>% 
  ggplot(aes(x = album, color = artist, y = profanity_count)) +
  geom_point(position = position_dodge2(width = 1, preserve = "single")) +
  theme_hc(style = "darkunica") +
      theme(
        legend.position = "bottom",
        legend.box = "vertical",
        axis.text = element_text(color = "gray", size = 12),
        axis.title.x = element_blank()
      ) +
  ylim(0, NA) +
  labs(
    title = "Profanity count by song in each album",
    y = "Profanity count",
    color = "Artist:"
  )

genius_testy %>% 
  get_sentences() %$% 
  profanity_by(lyric, list(track_title, track_n, album, artist)) %>% 
  ggplot(aes(x = track_n, y = profanity_count, color = artist)) +
  facet_wrap(~album, scales = "free_x") +
  geom_point() +
  geom_path() +
  theme_hc(style = "darkunica") +
      theme(
        legend.position = "bottom",
        legend.box = "vertical",
        axis.text = element_text(color = "gray", size = 12),
        axis.text.x = element_blank()
      ) +
  ylim(0, NA) +
  labs(
    title = "Profanity count by song in each album",
    x = "Track",
    y = "Profanity count",
    color = "Artist:"
  )

```

```{r max_grab}
df_testing <- data.frame(
  word = c("blah", "again"),
  n = c(20, 12)
)

max(df_testing$n)
```


```{r nrc_album}
nrc_order <- c("positive", "negative",
               "anger", "fear", "anticipation",
               "trust", "surprise",
               "sadness", "joy", "disgust")

album_nrc <- function(lyrics_df){
  lyrics_df %>% 
    unnest_tokens(output = word, input = lyric, token = "words") %>% 
    inner_join(get_sentiments("nrc")) %>%
    count(album, sentiment) %>% 
    mutate(sentiment = fct_relevel(as.factor(sentiment), nrc_order)) %>% 
  mutate(cat = case_when(
    (sentiment == "positive" | sentiment == "negative") ~ "Sentiment",
    TRUE ~ "Emotion")
  ) %>% 
    ggplot(aes(x = n,
               y = sentiment,
               fill = album)) +
    facet_grid(vars(cat), scales = "free_y", space = "free_y") +
    geom_col(position = "dodge") +
    #theme_few() +
    theme_hc(style = "darkunica") +
    theme(legend.position = "bottom") +
    labs(
      title = paste("Sentiment analysis of select", {{artist_of_interest}}, "albums"),
      x = "Word count",
      y = "",
      fill = "Album"
    ) +
    scale_fill_brewer(palette = "Set3")
}

album_nrc(my_lyrics)

my_lyrics %>% 
  unnest_tokens(output = word, input = lyric, token = "words") %>% 
    inner_join(get_sentiments("nrc")) %>%
    count(album, sentiment, word) %>% 
    mutate(sentiment = fct_relevel(as.factor(sentiment), nrc_order)) %>% 
  mutate(cat = case_when(
    (sentiment == "positive" | sentiment == "negative") ~ "Sentiment",
    TRUE ~ "Emotion")
  ) %>% 
  group_by(album, sentiment) %>% 
  slice_max(order_by = n, n = 1)
```

```{r text_input_test}
listy <- c("'Demon, Days', 'Plasitc beach', 'The fall")
data.frame(
  album = c(unlist(str_split(listy, "'")))
)

listy_new <- c("Demon Days", "Plastic beach", "the fall")
data.frame(
  album = c(unlist(str_split(listy_new, ", ")))
)
```

```{r filtering_tests}
my_tokens <- my_lyrics %>% 
  unnest_tokens(output = word, input = lyric, token = "words")

my_tokens %>% 
  anti_join(stop_words, by = "word") %>%
  count(track_title, album, word) %>% 
  group_by(album) %>% 
  slice_max(order_by = n, n = 10)
```


